const validTextMP3Voices = {
  Zeina: "Arabic / Zeina",
  Russell: "Australian English / Russell",
  Nicole: "Australian English / Nicole",
  Vitoria: "Brazilian Portuguese / Vitória",
  Camila: "Brazilian Portuguese / Camila",
  Ricardo: "Brazilian Portuguese / Ricardo",
  Emma: "British English / Emma",
  Brian: "British English / Brian",
  Amy: "British English / Amy",
  Chantal: "Canadian French / Chantal",
  Conchita: "Castilian Spanish / Conchita",
  Lucia: "Castilian Spanish / Lucia",
  Enrique: "Castilian Spanish / Enrique",
  Zhiyu: "Chinese Mandarin / Zhiyu",
  Naja: "Danish / Naja",
  Mads: "Danish / Mads",
  Ruben: "Dutch / Ruben",
  Lotte: "Dutch / Lotte",
  Celine: "French / Céline",
  Lea: "French / Léa",
  Mathieu: "French / Mathieu",
  Hans: "German / Hans",
  Vicki: "German / Vicki",
  Marlene: "German / Marlene",
  Dora: "Icelandic / Dóra",
  Karl: "Icelandic / Karl",
  Aditi: "Indian English / Aditi",
  Raveena: "Indian English / Raveena",
  Bianca: "Italian / Bianca",
  Carla: "Italian / Carla",
  Giorgio: "Italian / Giorgio",
  Takumi: "Japanese / Takumi",
  Mizuki: "Japanese / Mizuki",
  Seoyeon: "Korean / Seoyeon",
  Mia: "Mexican Spanish / Mia",
  Liv: "Norwegian / Liv",
  Jacek: "Polish / Jacek",
  Jan: "Polish / Jan",
  Maja: "Polish / Maja",
  Ewa: "Polish / Ewa",
  Cristiano: "Portuguese / Cristiano",
  Ines: "Portuguese / Inês",
  Carmen: "Romanian / Carmen",
  Maxim: "Russian / Maxim",
  Tatyana: "Russian / Tatyana",
  Astrid: "Swedish / Astrid",
  Filiz: "Turkish / Filiz",
  Salli: "US English / Salli",
  Ivy: "US English / Ivy",
  Joey: "US English / Joey",
  Matthew: "US English / Matthew",
  Kimberly: "US English / Kimberly",
  Kendra: "US English / Kendra",
  Justin: "US English / Justin",
  Joanna: "US English / Joanna",
  Lupe: "US Spanish / Lupe",
  Penelope: "US Spanish / Penélope",
  Miguel: "US Spanish / Miguel",
  Gwyneth: "Welsh / Gwyneth",
  Geraint: "Welsh English / Geraint",
};

export default validTextMP3Voices;
